# Site settings 配置站点
title: 'Minerva'
description: 'Minerva is the goddess of wisdom in ancient Rome. Here for inpiration and idea spreading.'
keyword: 'machine learning, deep learning, and my life'
url: 'http://pickou.cn' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Author 配置博主信息
author: 'jcyan'
nickname: '二骚'
bio: 'Lived it, love it!'
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: false

# Comments
disqus: false
disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  #weibo: '//weibo.com/lovecolcol'
  #juejin: '//juejin.im/user/57a6f434165abd006159b4cc'
  #instagram: '//www.instagram.com/steveliaocn'
  github: '//github.com/pickou'
  zhihu: '//www.zhihu.com/people/jackyan-55/activities'
  linkedin: '//www.linkedin.com/in/%E4%BF%8A%E8%B6%85-%E9%A2%9C-524914144/'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6 
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: none #rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

RSS: false

# Plugins
plugins: [jekyll-paginate]
